### ISSUE TITLE
What about the actual talk ?

### ISSUE THREAD

**Issue by jzarca01** [elevatebart/autodocs-talk#1]
Hi @elevatebart 
This subject is very promising, where can we read/watch the actual talk ?

**Comment by elevatebart** [comment]
Talk is tonight, I will try to get it on tape so we can upload it ;)

**Comment by elevatebart** [comment]
Check the readme. I took the video of my screen but the sound is really awful so I keep it to myself.

Contact me if you feel adventurous ;)

**Comment by elevatebart** [comment]
You will get your wish as I am going to give the same talk at VueConf.us in March and it will be filmed.

**Comment by jzarca01** [comment]
Congrats Bart !
